### ISSUE TITLE
Change 'Trent' to 'Trend' in main description

### ISSUE THREAD

**Issue by bhashish90** [brienzb/toy-box#307]
Hi,

This is just a simple spelling error that I have highlighted, change 'Trent' to 'Trend' in your main description.

Many thanks,
Ashish B

**Comment by brienzb** [comment]
Hi, @bhashish90 :)

Thank you so much for catching that! I’ve corrected the error thanks to your helpful feedback. I really appreciate your attention to detail. 😊

Best regards,
brienzb
